config/routes.rb
Rails.application.routes.draw do
  root 'gripes#index'
  resources :gripes  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gripe.rb
class Gripe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gripes_controller.rb
class GripesController < ApplicationController

  def index
    @gripes = Gripe.all
  end

  def new
    @gripe = Gripe.new
  end

  def create
    Gripe.create(place_params)
    redirect_to root_path
  end

  private

  def place_params
    params.require(:gripe).permit(:name, :beef, :fix)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gripes_helper.rb
module GripesHelper
end

app/views/gripes/index.html.erb
<% @gripes.each do |gripe| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= gripe.name %></h1>
    <i><%= gripe.beef %></i><br /><br />
    <p><%= gripe.fix %></p><br />
  </div>
<% end %>

app/views/gripes/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Beef Details</h1>
  <%= simple_form_for @gripe do |f| %>
    <%= f.input :name %>
    <%= f.input :beef %>
    <%= f.input :fix %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>cope to chill</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- a class="navbar-brand" href="#">Cope to chill</a> -->
  <%= link_to 'cope to chill', root_path, class: 'navbar-brand' %>


  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item">
<!--         <a class="nav-link" href="#">Link</a> -->
        <%= link_to 'New Gripe', new_gripe_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

    <%= yield %>
  </body>
</html>